apiVersion: v1
kind: Service
metadata:
  name: ghost
spec:
  selector:
    app: ghost
  ports:
  - port: 80
    targetPort: 2368
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0   #your IP here.